# Autorka: Kinga Markowska nr. indeksu: 164407

**Wprowadzenie do zbioru danych seriali anime (17562 tytułów (obiektów))**
https://www.kaggle.com/datasets/hernan4444/anime-recommendation-database-2020

 **PROBLEM:**

**Ocena popularności anime na podstawie
liczby osób oglądających - Regresja**

# ***Szczegółowe wprowadzenie kolumn (atrybutów warunkowych)***


---


Baza danych zawiera główne informacje na temat każdego serialu (17.562 różnych) takich jak: genre (kategoria), Type (typ) itp.

Baza ta zawiera poniższe atrybuty warunkowe (kolumny):

* **MAL_ID**: Identyfikator ze strony "MyAnimelist" danego serialu anime. (np. 1)

* **Name**: Pełna nazwa serialu anime. (np. Cowboy Bebop)

* **Score**: Przecięty wynik serialu anime dany od wszystkicg użytkowników na bazie danych "MyAnimelist". (np. 8.78)

* **Genres**: kategorie serialu anime wypisane w formie listy każde po przecinku (np. Action, Adventure, Comedy, Drama, Sci-Fi, Space)

* **English name**: Pełna nazwa serialu anime w języku angielskim (np. Cowboy Bebop)

* **Japanese name**: Pełna nazwa serialu anime w języku japońskim (np. カウボーイビバップ)

* **Type**: jeden z typów serialu anime: TV, movie, OVA, etc. (np. TV)

* **Episodes**: liczba odcinków (np. 26)

* **Aired**: data wypuszczenia serialu anime. (np. Apr 3, 1998 to Apr 24, 1999)

* **Premiered**: sezon premiery. (np. Spring 1998)

* **Producers**: lista producentów (np. Bandai Visual)

* **Licensors**: lista licencjodawców (np. Funimation, Bandai Entertainment)

* **Studios**: lista studiów produkujących serial anime (np. Sunrise)

* **Source**: Źródło: Manga, Light novel, Book, itd.. (np. Original)

* **Duration**: długość trwania odcinka serialu anime (np. 24 min. per ep.)

* **Rating**: klasyfikacja wiekowa (np. R - 17+ (violence & profanity))

* **Ranked**: pozycja oparta na punktacji serialu anime. (np. 28)

* **Popularity**: pozycja oparta na liczbie użytkowników, którzy dodali serial anime do swojej listy (np. 39)

* **Members**: liczba członków w grupie danego serialu anime (np. 1251960)

* **Favorites**: liczba użytkowników, którzy mają serial anime dodany do "ulubionych" (np. 61,971)

* **Watching**: liczba użytkowników, którzy są w trakcie oglądania serialu anime (np. 105808)

* **Completed**: liczba użytkowników, którzy ukończyli oglądanie serialu anime (np. 718161)

* **On-Hold**: liczba użytkowników, którzy wstrzymali oglądanie serialu anime. (np. 71513)

* **Dropped**: liczba użytkowników, którzy porzucili oglądanie serialu anime. (np. 26678)

* **Plan to Watch**: liczba użytkowników, którzy planują obejrzeć serial anime (np. 329800)

* **Score-10**: liczba użytkowników, którzy ocenili serial anime na 10 punktów. (np. 229170)

* **Score-9**: liczba użytkowników, którzy ocenili serial anime na 9 punktów. (np. 182126)

* **Score-8**: liczba użytkowników, którzy ocenili serial anime na 8 punktów. (np. 131625)

* **Score-7**: liczba użytkowników, którzy ocenili serial anime na 7 punktów. (np. 62330)

* **Score-6**: liczba użytkowników, którzy ocenili serial anime na 6 punktów. (np. 20688)

* **Score-5**: liczba użytkowników, którzy ocenili serial anime na 5 punktów. (np. 8904)

* **Score-4**: liczba użytkowników, którzy ocenili serial anime na 4 punkty. (np. 3184)

* **Score-3**: liczba użytkowników, którzy ocenili serial anime na 3 punkty. (np. 1357)

* **Score-2**: liczba użytkowników, którzy ocenili serial anime na 2 punkty. (np. 741)

* **Score-1**: liczba użytkowników, którzy ocenili serial anime na 1 punkt. (np. 1580)

---

Ostatecznie po oczyszczeniu bazy znajdują się w niej takie atrybuty warunkowe:

* **Type**: jeden z typów serialu anime: TV, movie, OVA, etc. (np. TV)

* **Popularity**: pozycja oparta na liczbie użytkowników, którzy dodali serial anime do swojej listy (np. 39)

* **Members**: liczba członków w grupie danego serialu anime (np. 1251960)

* **Favorites**: liczba użytkowników, którzy mają serial anime dodany do "ulubionych" (np. 61,971)

* **Watching**: liczba użytkowników, którzy są w trakcie oglądania serialu anime (np. 105808)

            ^ **to bedzie atrybut decyzyjny**
            |

  
* **Completed**: liczba użytkowników, którzy ukończyli oglądanie serialu anime (np. 718161)

* **On-Hold**: liczba użytkowników, którzy wstrzymali oglądanie serialu anime. (np. 71513)

* **Dropped**: liczba użytkowników, którzy porzucili oglądanie serialu anime. (np. 26678)

* **Plan to Watch**: liczba użytkowników, którzy planują obejrzeć serial anime (np. 329800)

* **Score-10**: liczba użytkowników, którzy ocenili serial anime na 10 punktów. (np. 229170)

---

Atrybutem kategorialnym jest **Type**, reszta atrybutów to atrybuty numeryczne

# **ZAŁADOWANIE DANYCH**

In [ ]:
import pandas as pd # import biblioteki pandas do analizy i przetwarzania danych, używana przez słowo klucz 'pd'
import numpy as np # import biblioteki numpy do wyrażeń matematycznych itp. , używana przez słowo klucz 'np'

In [ ]:
file_path = '/content/drive/MyDrive/Colab Notebooks/database_project/anime_data.csv' # sciezka pliku csv z danymi do analizy i przetwarzania danych

In [ ]:
import os # import biblioteki os do analizy plikow systemowych

# jezeli w katalogu znajduje sie plik o danej nazwie to go wczytaj, jezeli nie to wczytaj plik ze sciezki (z colab z dysku)
if os.path.isfile("anime_data.csv"):
    anime_data = pd.read_csv("anime_data.csv")
else:
    anime_data = pd.read_csv(file_path, delimiter=",")

In [ ]:
anime_data # pokazanie bazy danych

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,...,Score-10,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",Cowboy Bebop,カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,...,229170.0,182126.0,131625.0,62330.0,20688.0,8904.0,3184.0,1357.0,741.0,1580.0
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Cowboy Bebop:The Movie,カウボーイビバップ 天国の扉,Movie,1,"Sep 1, 2001",Unknown,...,30043.0,49201.0,49505.0,22632.0,5805.0,1877.0,577.0,221.0,109.0,379.0
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",Trigun,トライガン,TV,26,"Apr 1, 1998 to Sep 30, 1998",Spring 1998,...,50229.0,75651.0,86142.0,49432.0,15376.0,5838.0,1965.0,664.0,316.0,533.0
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",Witch Hunter Robin,Witch Hunter ROBIN (ウイッチハンターロビン),TV,26,"Jul 2, 2002 to Dec 24, 2002",Summer 2002,...,2182.0,4806.0,10128.0,11618.0,5709.0,2920.0,1083.0,353.0,164.0,131.0
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",Beet the Vandel Buster,冒険王ビィト,TV,52,"Sep 30, 2004 to Sep 29, 2005",Fall 2004,...,312.0,529.0,1242.0,1713.0,1068.0,634.0,265.0,83.0,50.0,27.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17557,48481,Daomu Biji Zhi Qinling Shen Shu,Unknown,"Adventure, Mystery, Supernatural",Unknown,盗墓笔记之秦岭神树,ONA,Unknown,"Apr 4, 2021 to ?",Unknown,...,Unknown,Unknown,Unknown,1.0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
17558,48483,Mieruko-chan,Unknown,"Comedy, Horror, Supernatural",Unknown,見える子ちゃん,TV,Unknown,2021 to ?,Unknown,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
17559,48488,Higurashi no Naku Koro ni Sotsu,Unknown,"Mystery, Dementia, Horror, Psychological, Supe...",Higurashi:When They Cry – SOTSU,ひぐらしのなく頃に卒,TV,Unknown,"Jul, 2021 to ?",Summer 2021,...,1.0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
17560,48491,Yama no Susume: Next Summit,Unknown,"Adventure, Slice of Life, Comedy",Unknown,ヤマノススメ Next Summit,TV,Unknown,Unknown,Unknown,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
17561,48492,Scarlet Nexus,Unknown,"Action, Fantasy",Unknown,SCARLET NEXUS,TV,Unknown,"Jul, 2021 to ?",Summer 2021,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown

Wartości wybrakowane w danych są oznaczone jako "Unknown"

# **ANALIZA + OCZYSZCZANIE DANYCH**

In [ ]:
print("Kolumna: ilość 'Unknown' - procent\n")

for column in anime_data.columns:
    unknown_count = (anime_data[column] == 'Unknown').sum()
    print(f"{column}: {unknown_count} - {round((unknown_count/anime_data.shape[0]) * 100)}% \n")

Kolumna: ilość 'Unknown' - procent

MAL_ID: 0 - 0%

Name: 0 - 0%

Score: 5141 - 29%

Genres: 63 - 0%

English name: 10565 - 60%

Japanese name: 48 - 0%

Type: 37 - 0%

Episodes: 516 - 3%

Aired: 309 - 2%

Premiered: 12817 - 73%

Producers: 7794 - 44%

Licensors: 13616 - 78%

Studios: 7079 - 40%

Source: 3567 - 20%

Duration: 555 - 3%

Rating: 688 - 4%

Ranked: 1762 - 10%

Popularity: 0 - 0%

Members: 0 - 0%

Favorites: 0 - 0%

Watching: 0 - 0%

Completed: 0 - 0%

On-Hold: 0 - 0%

Dropped: 0 - 0%

Plan to Watch: 0 - 0%

Score-10: 437 - 2%

Score-9: 3167 - 18%

Score-8: 1371 - 8%

Score-7: 503 - 3%

Score-6: 511 - 3%

Score-5: 584 - 3%

Score-4: 977 - 6%

Score-3: 1307 - 7%

Score-2: 1597 - 9%

Score-1: 459 - 3%

In [ ]:
print("Kolumny, których ilość wartości 'Unknown' jest mniejsza rowna od ok.2%:\n")

for column in anime_data.columns:
    unknown_count = (anime_data[column] == 'Unknown').sum()
    if round((unknown_count/anime_data.shape[0]) * 100) <= 2:
      print(f"{column}: {unknown_count} - {round((unknown_count/anime_data.shape[0]) * 100)}%\n")

Kolumny, których ilość wartości 'Unknown' jest mniejsza rowna od ok.2%:

MAL_ID: 0 - 0%

Name: 0 - 0%

Genres: 63 - 0%

Japanese name: 48 - 0%

Type: 37 - 0%

Aired: 309 - 2%

Popularity: 0 - 0%

Members: 0 - 0%

Favorites: 0 - 0%

Watching: 0 - 0%

Completed: 0 - 0%

On-Hold: 0 - 0%

Dropped: 0 - 0%

Plan to Watch: 0 - 0%

Score-10: 437 - 2%

In [ ]:
# utworzenie pustej listy, w ktorej beda przechowywane nazwy kolumn do usuniecia
cols_to_drop = []

# dla kazdej kolumny, ktora procent wartosci
# 'Unknown' ma wiekszy od 2 - dodaje do listy 'cols_to_drop'
for column in anime_data.columns:
    unknown_count = (anime_data[column] == 'Unknown').sum()
    unknown_percent = round(unknown_count/anime_data.shape[0] * 100)
    if unknown_percent > 2:
        cols_to_drop.append(column)

print("Kolumny do usunięcia z powodu przekroczenia 2% wartosci 'Unknown':")
print(cols_to_drop)

Kolumny do usunięcia z powodu przekroczenia 2% wartosci 'Unknown':
['Score', 'English name', 'Episodes', 'Premiered', 'Producers', 'Licensors', 'Studios', 'Source', 'Duration', 'Rating', 'Ranked', 'Score-9', 'Score-8', 'Score-7', 'Score-6', 'Score-5', 'Score-4', 'Score-3', 'Score-2', 'Score-1']

In [ ]:
anime_data.drop(columns=cols_to_drop, inplace=True) # usuniecie kolumn z duza iloscia wartosci wybrakowanych (powyzej 2%)
anime_data.drop(columns=["Japanese name", "Aired", "MAL_ID", "Genres"], inplace=True) # usuniecie kolumn niepotrzebnych w analizie - "Japanese name", "Aired" i"MAL_ID"

In [ ]:
anime_data.replace('Unknown', np.NaN, inplace=True) # zastapienie wartosci 'Unknown' wartosciami NaN

In [ ]:
anime_data # pokazanie danych

,Name,Type,Popularity,Members,Favorites,Watching,Completed,On-Hold,Dropped,Plan to Watch,Score-10
0,Cowboy Bebop,TV,39,1251960,61971,105808,718161,71513,26678,329800,229170.0
1,Cowboy Bebop: Tengoku no Tobira,Movie,518,273145,1174,4143,208333,1935,770,57964,30043.0
2,Trigun,TV,201,558913,12944,29113,343492,25465,13925,146918,50229.0
3,Witch Hunter Robin,TV,1467,94683,587,4300,46165,5121,5378,33719,2182.0
4,Bouken Ou Beet,TV,4369,13224,18,642,7314,766,1108,3394,312.0
...,...,...,...,...,...,...,...,...,...,...,...
17557,Daomu Biji Zhi Qinling Shen Shu,ONA,13116,354,6,0,0,0,0,354,NaN
17558,Mieruko-chan,TV,17562,7010,70,14,0,14,0,6982,NaN
17559,Higurashi no Naku Koro ni Sotsu,TV,17558,11309,48,3,0,0,0,11306,1.0
17560,Yama no Susume: Next Summit,TV,17565,1386,2,13,2,2,1,1368,NaN
17561,Scarlet Nexus,TV,17563,310,0,4,0,1,1,304,NaN

In [ ]:
anime_data['Score-10'] = anime_data['Score-10'].apply(lambda x: str(x).replace('.0', '') if pd.notna(x) else x) # usuniecie koncowki .0 przy wartosciach dla atrybutu "Score-10"
anime_data['Score-10'] = pd.to_numeric(anime_data['Score-10'], errors='coerce').astype('Int64') # konwersja na Int64

In [ ]:
anime_data.dtypes # typy atrybutów warunkowych w bazie danych

Name             object
Type             object
Popularity        int64
Members           int64
Favorites         int64
Watching          int64
Completed         int64
On-Hold           int64
Dropped           int64
Plan to Watch     int64
Score-10          Int64
dtype: object

In [ ]:
print("Nazwa kolumny: wartosc <typ wartosci>\n")
for column in anime_data.columns:
  print(column + ": " + str(anime_data[column][0]) + "  "  + str(type(anime_data[column][0])))

Nazwa kolumny: wartosc <typ wartosci>

Name: Cowboy Bebop  <class 'str'>
Type: TV  <class 'str'>
Popularity: 39  <class 'numpy.int64'>
Members: 1251960  <class 'numpy.int64'>
Favorites: 61971  <class 'numpy.int64'>
Watching: 105808  <class 'numpy.int64'>
Completed: 718161  <class 'numpy.int64'>
On-Hold: 71513  <class 'numpy.int64'>
Dropped: 26678  <class 'numpy.int64'>
Plan to Watch: 329800  <class 'numpy.int64'>
Score-10: 229170  <class 'numpy.int64'>

In [ ]:
anime_data.isnull().any() # pokazuje, w ktorych kolumnach (atrybutach warunkowych) pojawia sie wartosc wybrakowana przynajmniej raz

Name             False
Type              True
Popularity       False
Members          False
Favorites        False
Watching         False
Completed        False
On-Hold          False
Dropped          False
Plan to Watch    False
Score-10          True
dtype: bool

In [ ]:
print("Ilość wybrakowanych wartości dla każdej kolumny po wstepnym\nusunieciu niepotrzebnych i bardzo wybrakowanych atrybutów warunkowych + typ wartości:\n")
for column in anime_data.columns:
  print(f'{column} -> {anime_data.loc[anime_data[column].isnull()].shape[0]}\
  \n[ok.{round((anime_data.loc[anime_data[column].isnull()].shape[0]/anime_data.shape[0]) * 100)} %] {type(anime_data[column][0])}\n')

Ilość wybrakowanych wartości dla każdej kolumny po wstepnym
usunieciu niepotrzebnych i bardzo wybrakowanych atrybutów warunkowych + typ wartości:

Name -> 0
[ok.0 %] <class 'str'>

Type -> 37
[ok.0 %] <class 'str'>

Popularity -> 0
[ok.0 %] <class 'numpy.int64'>

Members -> 0
[ok.0 %] <class 'numpy.int64'>

Favorites -> 0
[ok.0 %] <class 'numpy.int64'>

Watching -> 0
[ok.0 %] <class 'numpy.int64'>

Completed -> 0
[ok.0 %] <class 'numpy.int64'>

On-Hold -> 0
[ok.0 %] <class 'numpy.int64'>

Dropped -> 0
[ok.0 %] <class 'numpy.int64'>

Plan to Watch -> 0
[ok.0 %] <class 'numpy.int64'>

Score-10 -> 437
[ok.2 %] <class 'numpy.int64'>

# **OCZYSZCZANIE + PODZIAŁ + TRANSFORMACJA DANYCH**

In [ ]:
# wczytanie biblioteki sklearn
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, StandardScaler, OneHotEncoder, FunctionTransformer, MinMaxScaler

In [ ]:
X = anime_data.iloc[:, anime_data.columns != 'Watching'] # X to cechy
y = anime_data['Watching'] # y to etykiety dla atrybutu warunkowego "Watching"

In [ ]:
X

,Name,Type,Popularity,Members,Favorites,Completed,On-Hold,Dropped,Plan to Watch,Score-10
0,Cowboy Bebop,TV,39,1251960,61971,718161,71513,26678,329800,229170
1,Cowboy Bebop: Tengoku no Tobira,Movie,518,273145,1174,208333,1935,770,57964,30043
2,Trigun,TV,201,558913,12944,343492,25465,13925,146918,50229
3,Witch Hunter Robin,TV,1467,94683,587,46165,5121,5378,33719,2182
4,Bouken Ou Beet,TV,4369,13224,18,7314,766,1108,3394,312
...,...,...,...,...,...,...,...,...,...,...
17557,Daomu Biji Zhi Qinling Shen Shu,ONA,13116,354,6,0,0,0,354,<NA>
17558,Mieruko-chan,TV,17562,7010,70,0,14,0,6982,<NA>
17559,Higurashi no Naku Koro ni Sotsu,TV,17558,11309,48,0,0,0,11306,1
17560,Yama no Susume: Next Summit,TV,17565,1386,2,2,2,1,1368,<NA>
17561,Scarlet Nexus,TV,17563,310,0,0,1,1,304,<NA>

In [ ]:
X = X.drop(columns=['Name']) # usuwanie atrybutu "Name", poniewaz nie wnosi on uzytecznych informacji do modelu predykcyjnego

In [ ]:
num_attr = X.select_dtypes(include=['number']).columns.tolist() # numeryczne atrybuty
cat_attr = X.select_dtypes(exclude=['number']).columns.tolist() # kategorialne atrybuty

In [ ]:
# lista cech numerycznych i kategorialnych
print("Numeryczne cechy:", num_attr)
print("Kategorialne cechy:", cat_attr)

Numeryczne cechy: ['Popularity', 'Members', 'Favorites', 'Completed', 'On-Hold', 'Dropped', 'Plan to Watch', 'Score-10']
Kategorialne cechy: ['Type']

Name: Usuniemy ten atrybut, ponieważ nie wnosi on użytecznych informacji do modelu predykcyjnego.

Atrybuty kategorialne **"Genres"** i **"Type"**:

Kodowanie atrybutów za pomocą OneHotEncoder do stworzenia binarnych kolumn dla każdego gatunku.

In [ ]:
"""# Funkcja do zastępowania wartosci w atrybucie "Genres"
# tylko przez pierwszy gatunek przed przecinkiem z pomoca funkcji lambda
def extract_first_genre(X):
    X['Genres'] = X['Genres'].apply(lambda x: x.split(',')[0] if isinstance(x, str) else x)
    return X
"""

'# Funkcja do zastępowania wartosci w atrybucie "Genres"\n# tylko przez pierwszy gatunek przed przecinkiem z pomoca funkcji lambda\ndef extract_first_genre(X):\n    X[\'Genres\'] = X[\'Genres\'].apply(lambda x: x.split(\',\')[0] if isinstance(x, str) else x)\n    return X\n'

In [ ]:
# potok dla przetwarzania kategorialnych cech: 'SimpleImputer'
# ze strategia najczesciej pojawiajacych sie wartosci do oczyszczania
# wybrakowanych wartosci, oraz encoder 'OneHotEncoder' do wyznaczania wartosci
# 1 lub 0 dla danej wartosci w kolumnie kategorialnej
cat_pipeline = Pipeline([
    #('extract_first_genre', FunctionTransformer(extract_first_genre)),
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

In [ ]:
# potok dla przetwarzania numerycznych cech: 'SimpleImputer' do uzupelnienia
# wartosci wybrakowanych mediana
num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
])

In [ ]:
# zastosowanie potoku dla roznych typow cech
preprocessor = ColumnTransformer([
    ('num', num_pipeline, num_attr),
    ('cat', cat_pipeline, cat_attr)
])

In [ ]:
# transformacja danych
transformed_data = preprocessor.fit_transform(X)

In [ ]:
transformed_data.shape # rozmiar danych po oczyszczaniu i transformacji wartosci

(17562, 14)

In [ ]:
y # etykiety -> atrybut decyzyjny

0        105808
1          4143
2         29113
3          4300
4           642
          ...
17557         0
17558        14
17559         3
17560        13
17561         4
Name: Watching, Length: 17562, dtype: int64

In [ ]:
# polaczenie ramek danych w jedno - 'OneHotEncoder' zwraca
# macierz rzadka -> konwersja do DataFrame
transformed_data_df = pd.DataFrame(transformed_data, columns=num_attr + list(preprocessor.named_transformers_['cat']['onehot'].get_feature_names_out(cat_attr)))

In [ ]:
transformed_data_df

,Popularity,Members,Favorites,Completed,On-Hold,Dropped,Plan to Watch,Score-10,Type_Movie,Type_Music,Type_ONA,Type_OVA,Type_Special,Type_TV
0,39.0,1251960.0,61971.0,718161.0,71513.0,26678.0,329800.0,229170.0,0.0,0.0,0.0,0.0,0.0,1.0
1,518.0,273145.0,1174.0,208333.0,1935.0,770.0,57964.0,30043.0,1.0,0.0,0.0,0.0,0.0,0.0
2,201.0,558913.0,12944.0,343492.0,25465.0,13925.0,146918.0,50229.0,0.0,0.0,0.0,0.0,0.0,1.0
3,1467.0,94683.0,587.0,46165.0,5121.0,5378.0,33719.0,2182.0,0.0,0.0,0.0,0.0,0.0,1.0
4,4369.0,13224.0,18.0,7314.0,766.0,1108.0,3394.0,312.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17557,13116.0,354.0,6.0,0.0,0.0,0.0,354.0,39.0,0.0,0.0,1.0,0.0,0.0,0.0
17558,17562.0,7010.0,70.0,0.0,14.0,0.0,6982.0,39.0,0.0,0.0,0.0,0.0,0.0,1.0
17559,17558.0,11309.0,48.0,0.0,0.0,0.0,11306.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
17560,17565.0,1386.0,2.0,2.0,2.0,1.0,1368.0,39.0,0.0,0.0,0.0,0.0,0.0,1.0
17561,17563.0,310.0,0.0,0.0,1.0,1.0,304.0,39.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
X = transformed_data_df # ustawienie ramki danych na cechy

In [ ]:
# podzial danych na trening i test -> 80% - 20% po oczyszczeniu danych
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
X.shape # wymiary danych po oczyszczeniu i transformacji

(17562, 14)

In [ ]:
y_test

16011       309
7074         22
6983         15
7293        520
8020       3817
          ...
9228         11
817         494
17470        44
4073         51
15046    112840
Name: Watching, Length: 3513, dtype: int64

In [ ]:
X.isnull().any() # po tym brak wartosci wybrakowanych

Popularity       False
Members          False
Favorites        False
Completed        False
On-Hold          False
Dropped          False
Plan to Watch    False
Score-10         False
Type_Movie       False
Type_Music       False
Type_ONA         False
Type_OVA         False
Type_Special     False
Type_TV          False
dtype: bool

# **CZĘŚĆ 2**

_________________________________

- Im niższa wartość MSE, tym lepiej. Oznacza to, że przewidywania są bliższe rzeczywistym wartościom
- Podobnie jak w przypadku MSE, im niższa wartość MAE, tym lepiej. Oznacza to, że przewidywania są bliższe rzeczywistym wartościom.
- Wartość R^2 mieści się w zakresie od 0 do 1. Im bliżej R^2 do 1, tym lepiej. Oznacza to, że model lepiej wyjaśnia zmienność danych.

In [ ]:
# import biblioteki sklearn
from sklearn.pipeline import make_pipeline
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

#from sklearn.neighbors import KNeighborsRegressor

In [ ]:
"""MODEL: Regresja Liniowa (bez hiperparametrów)"""

# tworzenie potoku przetwarzania danych
linear_pipeline = Pipeline([
    ('scaler', StandardScaler()),  # skalowanie cech
    ('regressor', LinearRegression())  # model regresji liniowej
])

# dopasowanie modelu
linear_pipeline.fit(X_train, y_train)

# predykcja na zbiorze testowym
y_pred_linear = linear_pipeline.predict(X_test)

# obliczenie miar jakosci modelu
mse = mean_squared_error(y_test, y_pred_linear)
mae = mean_absolute_error(y_test, y_pred_linear)
r2 = r2_score(y_test, y_pred_linear)

print(f"Blad sredniokwadratowy Linear Regression(MSE): {mse:.2f} ({mse})")
print(f"Sredni blad bezwzgledny Linear Regression(MAE): {mae:.2f} ({mae})")
print(f"R kwadrat Linear Regression(R2): {r2}")

Blad sredniokwadratowy Linear Regression(MSE): 0.00 (4.455400779676991e-21)
Sredni blad bezwzgledny Linear Regression(MAE): 0.00 (4.603912405814968e-11)
R kwadrat Linear Regression(R2): 1.0

Blad sredniokwadratowy Linear Regression(MSE): 0.00 (4.455400779676991e-21)
Sredni blad bezwzgledny Linear Regression(MAE): 0.00 (4.603912405814968e-11)
R kwadrat Linear Regression(R2): 1.0

Najlepszym modelem będzie regresja liniowa - wartosci MSE i MAE są bliskie zeru

In [ ]:
"""MODEL: Regresja Liniowa (z hiperparametrami)"""

# definicja siatki hiperparametrow do przeszukania
param_grid_linear = {
    'regressor__fit_intercept': [True, False],
}

# utworzenie obiektu Grid Search Walidacji krzyżowej
grid_search_linear = GridSearchCV(linear_pipeline, param_grid_linear, cv=5, scoring='neg_mean_squared_error', n_jobs=-1)

# dopasowanie modelu z optymalnymi hiperparametrami
grid_search_linear.fit(X_train, y_train)

# wybor najlepszego modelu
best_linear_model = grid_search_linear.best_estimator_

# przewidywanie na zbiorze testowym
y_pred_best_linear = best_linear_model.predict(X_test)

# obliczenie miar jakosci modelu dla najlepszego modelu
mse_best_linear = mean_squared_error(y_test, y_pred_best_linear)
mae_best_linear = mean_absolute_error(y_test, y_pred_best_linear)
r2_best_linear = r2_score(y_test, y_pred_best_linear)

print(f"Best Linear Regression (MSE): {mse_best_linear:.2f} ({mse_best_linear})")
print(f"Best Linear Regression (MAE): {mae_best_linear:.2f} ({mae_best_linear})")
print(f"Best Linear Regression (R2): {r2_best_linear:.2f}")

Best Linear Regression (MSE): 0.00 (4.455400779676991e-21)
Best Linear Regression (MAE): 0.00 (4.603912405814968e-11)
Best Linear Regression (R2): 1.00

In [ ]:
grid_search_linear.best_params_ # najlepsze parametry wybrane dla regresji liniowej

{'regressor__fit_intercept': True}

Best Linear Regression (MSE): 0.00 (4.455400779676991e-21)
Best Linear Regression (MAE): 0.00 (4.603912405814968e-11)
Best Linear Regression (R2): 1.00

Tu również bez większych zmian przy modelu Regresji Liniowej - wartosci MSE i MAE są bliskie zeru a R^2 1

- Liniowa zależność
- Pierwszy krok do zrozumienia ogólnych  trendów

In [ ]:
"""MODEL: Las Losowy (bez hiperparametrów)"""

# tworzenie potoku dla Random Forest Regressor
rf_pipeline = Pipeline([
    ('scaler', StandardScaler()),  # skalowanie cech
    ('regressor', RandomForestRegressor())  # model lasu losowego
])

# dopasowanie modelu
rf_pipeline.fit(X_train, y_train)

# przewidywanie na zbiorze testowym
y_pred_rf = rf_pipeline.predict(X_test)

# obliczenie miar jakosci modelu
mse_rf = mean_squared_error(y_test, y_pred_rf)
mae_rf = mean_absolute_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)

print(f"Random Forest (MSE): {mse_rf:.2f} ({mse_rf})")
print(f"Random Forest (MAE): {mae_rf:.2f} ({mae_rf})")
print(f"Random Forest (R2): {r2_rf:.2f}")

Random Forest (MSE): 35624550.70 (35624550.70098636)
Random Forest (MAE): 702.24 (702.2392228864219)
Random Forest (R2): 0.85

Random Forest (MSE): 37194098.87 (37194098.87266422)
Random Forest (MAE): 708.48 (708.4793851409053)
Random Forest (R2): 0.84

Dla modelu Lasu Losowego dla Regresji Wartości dla MSE i MAE wyszły duże, gorzej niż Regresja Liniowa

In [ ]:
"""# MODEL: Las Losowy (z hiperparametrami) Z GridSearchCV -> Lepszy z RandomizedSearchCV ponizej

# Z hiperparametrami
# definicja siatki hiperparametrów do przeszukania
param_grid_rf = {
    'regressor__n_estimators': [50, 100],
    'regressor__max_depth': [None, 5, 10],
}

# Utworzenie obiektu Grid Search
grid_search_rf = GridSearchCV(rf_pipeline, param_grid_rf, cv=5, scoring='neg_mean_squared_error', n_jobs=-1)

# Dopasowanie modelu z optymalnymi hiperparametrami
grid_search_rf.fit(X_train, y_train)

# wybor najlepszego modelu
best_rf_model = grid_search_rf.best_estimator_

# predykcja na zbiorze testowym
y_pred_best_rf = best_rf_model.predict(X_test)

# obliczenie miar jakości modelu dla najlepszego modelu
mse_best_rf = mean_squared_error(y_test, y_pred_best_rf)
mae_best_rf = mean_absolute_error(y_test, y_pred_best_rf)
r2_best_rf = r2_score(y_test, y_pred_best_rf)

print("Optymalizacja")
print(f"Best Random Forest (MSE): {mse_best_rf:.2f} ({mse_best_rf})")
print(f"Best Random Forest (MAE): {mae_best_rf:.2f} ({mae_best_rf})")
print(f"Best Random Forest (R2): {r2_best_rf:.2f}")"""

# print(grid_search_rf.best_params_) #najlepsze parametry z walidacja krzyzowa na Lasie Losowym

'# MODEL: Las Losowy (z hiperparametrami) Z GridSearchCV -> Lepszy z RandomizedSearchCV ponizej\n\n# Z hiperparametrami\n# definicja siatki hiperparametrów do przeszukania\nparam_grid_rf = {\n    \'regressor__n_estimators\': [50, 100],\n    \'regressor__max_depth\': [None, 5, 10],\n}\n\n# Utworzenie obiektu Grid Search\ngrid_search_rf = GridSearchCV(rf_pipeline, param_grid_rf, cv=5, scoring=\'neg_mean_squared_error\', n_jobs=-1)\n\n# Dopasowanie modelu z optymalnymi hiperparametrami\ngrid_search_rf.fit(X_train, y_train)\n\n# wybor najlepszego modelu\nbest_rf_model = grid_search_rf.best_estimator_\n\n# predykcja na zbiorze testowym\ny_pred_best_rf = best_rf_model.predict(X_test)\n\n# obliczenie miar jakości modelu dla najlepszego modelu\nmse_best_rf = mean_squared_error(y_test, y_pred_best_rf)\nmae_best_rf = mean_absolute_error(y_test, y_pred_best_rf)\nr2_best_rf = r2_score(y_test, y_pred_best_rf)\n\nprint("Optymalizacja")\nprint(f"Best Random Forest (MSE): {mse_best_rf:.2f} ({mse_best_rf})")\nprint(f"Best Random Forest (MAE): {mae_best_rf:.2f} ({mae_best_rf})")\nprint(f"Best Random Forest (R2): {r2_best_rf:.2f}")'

In [ ]:
"""MODEL: Las Losowy (z hiperparametrami)
   + tu Walidacja krzyzowa z RandomizedSearchCV """
# definicja siatki hiperparametrow do przeszukania
param_dist_rf = {
    'regressor__n_estimators': [50, 100],
    'regressor__max_depth': [10, 15],
    'regressor__min_samples_split': [2, 5],
    'regressor__min_samples_leaf': [1, 2]
}

# utworzenie obiektu Randomized Search
random_search_rf = RandomizedSearchCV(rf_pipeline, param_distributions=param_dist_rf, cv=5, scoring='neg_mean_squared_error', n_iter=5, random_state=42, n_jobs=-1)

# Dopasowanie modelu z optymalnymi hiperparametrami
random_search_rf.fit(X_train, y_train)

# wybor najlepszego modelu
best_rf_model = random_search_rf.best_estimator_

# przewidywanie na zbiorze testowym
y_pred_best_rf = best_rf_model.predict(X_test)

# obliczenie miar jakosci modelu dla najlepszego modelu
mse_best_rf = mean_squared_error(y_test, y_pred_best_rf)
mae_best_rf = mean_absolute_error(y_test, y_pred_best_rf)
r2_best_rf = r2_score(y_test, y_pred_best_rf)

print("Optymalizacja")
print(f"Best Random Forest (MSE): {mse_best_rf:.2f} ({mse_best_rf})")
print(f"Best Random Forest (MAE): {mae_best_rf:.2f} ({mae_best_rf})")
print(f"Best Random Forest (R2): {r2_best_rf:.2f}")

# model laduje sie 2 minuty

Optymalizacja
Best Random Forest (MSE): 38011234.54 (38011234.54074755)
Best Random Forest (MAE): 718.89 (718.8929165918929)
Best Random Forest (R2): 0.84

In [ ]:
random_search_rf.best_params_ # najlepsze parametry wybrane dla lasu losowego

{'regressor__n_estimators': 100,
 'regressor__min_samples_split': 2,
 'regressor__min_samples_leaf': 1,
 'regressor__max_depth': 10}

Optymalizacja
Best Random Forest (MSE): 30780136.88 (30780136.881377876)
Best Random Forest (MAE): 679.42 (679.424077632841)
Best Random Forest (R2): 0.87

Dla Lasu Losowego wyszły wartosci wysokie dla MSE, MAE

- głębszy wgląd w złożone wzorce
- wykorzystuje większą ilość cech

In [ ]:
"""MODEL: Drzewo Decyzyjne (z hiperparametrami) """

# definicja zakresów hiperparametrow do przetestowania
param_dt = {
    'regressor__max_depth': [5, 10, 15, 20, None],
    'regressor__min_samples_split': [2, 5, 10],
    'regressor__min_samples_leaf': [1, 2, 4]
}

# tworzenie potoku dla Decision Tree Regressor
dt_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('regressor', DecisionTreeRegressor())
])

# utworzenie obiektu Grid Search Walidacji krzyzowej
grid_search_dt = GridSearchCV(dt_pipeline, param_dt, cv=5, scoring='neg_mean_squared_error', n_jobs=-1)

# dopasowanie modelu z optymalnymi hiperparametrami
grid_search_dt.fit(X_train, y_train)

# wybor najlepszego modelu
best_dt_model = grid_search_dt.best_estimator_

# przewidywanie na zbiorze testowym
y_pred_best_dt = best_dt_model.predict(X_test)

# obliczenie miar jakości modelu dla najlepszego modelu
mse_best_dt = mean_squared_error(y_test, y_pred_best_dt)
mae_best_dt = mean_absolute_error(y_test, y_pred_best_dt)
r2_best_dt = r2_score(y_test, y_pred_best_dt)

print(f"Best Decision Tree (MSE): {mse_best_dt:.2f} ({mse_best_dt})")
print(f"Best Decision Tree (MAE): {mae_best_dt:.2f} ({mae_best_dt})")
print(f"Best Decision Tree (R2): {r2_best_dt:.2f}")

Best Decision Tree (MSE): 24263260.32 (24263260.316684853)
Best Decision Tree (MAE): 839.93 (839.932536293766)
Best Decision Tree (R2): 0.90

In [ ]:
grid_search_dt.best_params_ # najlepsze parametry wybrane dla drzewa decyzyjnego

{'regressor__max_depth': None,
 'regressor__min_samples_leaf': 1,
 'regressor__min_samples_split': 5}

Best Decision Tree (MSE): 20749712.54 (20749712.5373478)
Best Decision Tree (MAE): 764.07 (764.07004895334)
Best Decision Tree (R2): 0.91

Podobnie dla modelu Drzewa decyzyjnego - Wartości dla MSE i MAE wyszły duże, gorzej niż Regresja Liniowa

- ułatwia zrozumienie jak poszczególne cechy wpływają na decyzje
- identyfikacja

Analizując wyniki i kod, można wyciągnąć następujące wnioski:

1. *Regresja Liniowa*:
   - Model regresji liniowej bez hiperparametrów oraz z optymalnymi hiperparametrami osiągnął doskonałe wyniki, z *MSE* i *MAE* bliskimi zeru oraz *R^2* równym 1.0. Wartości te sugerują, że model doskonale dopasował się do danych treningowych, przewidując wartości testowe z niemal absolutną dokładnością. Jednakże wyniki te mogą również wskazywać na przetrenowanie modelu.

2. *Las Losowy*:
   - Model lasu losowego bez hiperparametrów oraz z optymalnymi hiperparametrami wykazał gorsze wyniki w porównaniu z regresją liniową. *MSE* i *MAE* były znacznie wyższe, a *R^2* niższe (0.84 i 0.87). Wyniki te wskazują, że model lasu losowego nie był w stanie tak dokładnie przewidzieć wartości testowych, co może być spowodowane złożonością modelu.

3. *Drzewo Decyzyjne*:
   - Model drzewa decyzyjnego z optymalnymi hiperparametrami osiągnął *MSE* i *MAE* niższe niż las losowy, ale nadal wyższe niż regresja liniowa, z *R^2* na poziomie 0.91. Wyniki te sugerują, że drzewo decyzyjne było w stanie lepiej przewidzieć wartości testowe niż las losowy, ale nadal nie dorównuje dokładności regresji liniowej.

Regresja liniowa zatem wydaje się być najlepszym modelem dla tego zestawu danych, ale mogło dojść do przetrenowania.

________________________________________________________________________________